spring:
  profiles.active: local
  application:
     name: accounts_scs
  jpa:
     hibernate:
        ddl-auto: update

---
spring:
  profiles: local
server:
  port: 8082
eureka:
  instance:
    nonSecurePort: ${server.port}
